### ISSUE TITLE
Inverted PIN logic

### ISSUE THREAD

**Issue by RaptorHunterMZ** [linux-paul/OctoPrint-Heatbedsavety#3]
Hi, can you add an option to invert the logic of the pin, I want the relay to only be closed when the plugin receives the signal from the Pi.

**Comment by linux-paul** [comment]
Hi, I purposely not implemented this option, because it reduces the safety a lot.
The Bed is kept under power while the pi is not connected or powered down, this is not the very common way implementing safety.
But I'll see what I can do. May be I'll create an installation package on GitHub but not as an official release, is this OK?

**Comment by RaptorHunterMZ** [comment]
> The Bed is kept under power while the pi is not connected or powered down,

That's exactly what I want to do, I want the relay to stay open unless if the pi does gives a signal that temps are fine. 
Pi OFF (PI pin off) = Relay to heated bed Open (no power to bed)
Pi ON (PI pin on)= Relay to heated bed Closed (power to bed)
Pi ON + Over temperature (PI pin off) = Relay to heated bed Open (no power to bed)

**Comment by linux-paul** [comment]
> That's exactly what I want to do, I want the relay to stay open unless if the pi does gives a signal that temps are fine.
Pi OFF (PI pin off) = Relay to heated bed Open (no power to bed)
Pi ON (PI pin on)= Relay to heated bed Closed (power to bed)
Pi ON + Over temperature (PI pin off) = Relay to heated bed Open (no power to bed)

this is what the plugin usually does. 
Output high/on means the power is connected to the bed and the button color is green in this case.
Additionally the plugin checks the printer state and wait for "OPERATIONAL" after startup before the Pin goes to high.
"ERROR" and "CLOSED_WITH_ERROR" automatically switching off.

**Comment by RaptorHunterMZ** [comment]
I can never get the plugin to turn on the heated bed, I am using the pin 40 to control the relay.

**Comment by linux-paul** [comment]
Pushing the button should switch the output. The Pinnumbers are determined in BCM Mode. BOARD Mode Pin40 (CornerPin) is GPIO21 -> Pin21 BCM Mode.

**Comment by RaptorHunterMZ** [comment]
here is what I am getting from the logs:
2020-12-13 16:42:25,461 - octoprint.plugins.heatbedsavety - WARNING - GPIO already cleaned up

**Comment by linux-paul** [comment]
Have you set a valid Pin Number? "40" is not possible, because there is no Pin 40 in BCM.

**Comment by RaptorHunterMZ** [comment]
yes I changed the pin to GPIO22 (PIN15). What pin do you recommend?

**Comment by linux-paul** [comment]
So "22" have to be entered into the configuration, is it done like this?

**Comment by RaptorHunterMZ** [comment]
Yes I set it to 22.

**Comment by linux-paul** [comment]
pushing the button should switch the output. Have you checked your circuit by switching the IO from commandline?

**Comment by RaptorHunterMZ** [comment]
It's working now, I guess it was some incompatibility with the PSU control plugin it's working after disabling and enabling PSU control.

**Comment by RaptorHunterMZ** [comment]
Thank you for the support, great plugin.
